version: '2'

services:
    sonar:
        image: sonarqube:5.6.6-alpine
        ports:
            - "9001:9000"
        depends_on:
            - sonardb
        environment:
            - SONARQUBE_JDBC_URL=jdbc:mysql://sonardb:3306/sonar?useUnicode=true&characterEncoding=utf8
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonarmysql

    sonardb:
        image: mysql:5.7.17
        volumes:
            - ./data_mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: sonar
            MYSQL_USER: sonar
            MYSQL_PASSWORD: sonarmysql
            MYSQL_ROOT_PASSWORD: sonarroot

