version: '3.4'
services:
  nginx-proxy:
    image: nginx-proxy
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../dist:/usr/share/nginx/html
    ports:
      - 80:80
networks:
  default:
    external:
      name: local_network